### ISSUE TITLE
Support for Findings in Dashboards

### ISSUE THREAD

**Issue by chrisdunne** [cdktf/cdktf-provider-datadog#511]
Hi,

Will you be introducing support for security "Finding" queries in the Dashboard widgets?

https://constructs.dev/packages/@cdktf/provider-datadog/v/0.3.219/api/cdktfproviderdatadogdashboardwidgettoplistdefinitionrequest?lang=typescript

Thank you,

Chris

**Comment by DanielMSchmidt** [comment]
Hey @chrisdunne, sorry for the late relpy. This repo is a prebuilt providers that are generated from the [Terraform Provider](https://github.com/DataDog/terraform-provider-datadog). I couldn't find support there either, so one would need to open an issue there first and when it's fixed our provider will auto-update.
